#   --------------------------AUTH_USER---------------------------------
###
POST http://localhost:7000/auth/signup
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODc5OTNhNjE2OGY1MTIwNDRlOTQxMCIsImVtYWlsIjoic3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9VU0VSIiwiaWF0IjoxNjE5NTAxNTg5fQ.xwJSxamocUUc_g-bQ-a2Tv9MYvkCiIaq_Kwp4j8UR-E

{
    "email":"customer5@gmail.com",
    "name": "customer5",
    "age": 29,
    "role" : "CUSTOMER",
    "subscriptionId":"608908a78286c30b0447b3d5"
}

###
POST http://localhost:7000/auth/login
Content-Type: application/json

{
    "email":"superuser@gmail.com",
    "password" : "superuser"
  
}
###
GET  http://localhost:7000/auth/allUsers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODc5OTNhNjE2OGY1MTIwNDRlOTQxMCIsImVtYWlsIjoic3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9VU0VSIiwiaWF0IjoxNjE5NTA4NDYxfQ.W7DbtVHlYTO95wnEvsEOnHtol4Gg6SmWDQ0UeDtWaew


###
GET http://localhost:7000/auth/search/6087b6e6b66c2647bcbde238
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODc5OTNhNjE2OGY1MTIwNDRlOTQxMCIsImVtYWlsIjoic3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9VU0VSIiwiaWF0IjoxNjE5NTA4NDYxfQ.W7DbtVHlYTO95wnEvsEOnHtol4Gg6SmWDQ0UeDtWaew


###
PATCH http://localhost:7000/auth/updateUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODc5OTNhNjE2OGY1MTIwNDRlOTQxMCIsImVtYWlsIjoic3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9VU0VSIiwiaWF0IjoxNjE5NTA4NDYxfQ.W7DbtVHlYTO95wnEvsEOnHtol4Gg6SmWDQ0UeDtWaew

{
    "userId": "608e5b6035f9641c48bec662",
    "role" : "DELIVERY_BOY",
    "age": 41
}

#   -----------------------------UTILTY---------------------------------
###
POST http://localhost:7000/admin/utility
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODc5OTNhNjE2OGY1MTIwNDRlOTQxMCIsImVtYWlsIjoic3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9VU0VSIiwiaWF0IjoxNjE5NTA4NDYxfQ.W7DbtVHlYTO95wnEvsEOnHtol4Gg6SmWDQ0UeDtWaew

{
   "roles": ["SUPER_USER","ADMIN","DELIVERY_BOY","CUSTOMER"],
    "ratelist": [{"size":"1000ml", "price": 70},{"size":"500ml", "price": 40}],
   "subscriptions": [{"name":"WEEKLY", "price":600,"days":7},{"name":"BIWEEKLY", "price":1000,"days":15},{"name":"MONTHLY", "price":4000,"days":30}] 
}

###
PATCH  http://localhost:7000/admin/utility/updateRateList
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODc5OTNhNjE2OGY1MTIwNDRlOTQxMCIsImVtYWlsIjoic3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9VU0VSIiwiaWF0IjoxNjE5NTA4NDYxfQ.W7DbtVHlYTO95wnEvsEOnHtol4Gg6SmWDQ0UeDtWaew

{
    "ratelist": {"rateListId": "6088fc15c1a01b4d4c4f0d9c","size":"500ml", "price": 1000}
}

###
PATCH  http://localhost:7000/admin/utility/updateSubscription
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODc5OTNhNjE2OGY1MTIwNDRlOTQxMCIsImVtYWlsIjoic3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9VU0VSIiwiaWF0IjoxNjE5NTA4NDYxfQ.W7DbtVHlYTO95wnEvsEOnHtol4Gg6SmWDQ0UeDtWaew

{
    "subscription": {"subscriptionListId": "608a162fb0d0810e2856dde6","name":"DAILY", "days": 1, "price":100}
}

###
GET  http://localhost:7000/admin/utility
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODc5OTNhNjE2OGY1MTIwNDRlOTQxMCIsImVtYWlsIjoic3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9VU0VSIiwiaWF0IjoxNjE5NDk5ODExfQ.rIxt6YHoYms9OnAZuZJOKNvElKzyRgwstw5_-twsGLU


#   ---------------------------PAYMENT---------------------------------
###
POST http://localhost:7000/payments/createPayment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODc5OTNhNjE2OGY1MTIwNDRlOTQxMCIsImVtYWlsIjoic3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9VU0VSIiwiaWF0IjoxNjE5NTA4NDYxfQ.W7DbtVHlYTO95wnEvsEOnHtol4Gg6SmWDQ0UeDtWaew

{
    "userId":"608e589d1c164145787854ae",
    "paid": 2090,
    "dueAmount":0

}

###
POST http://localhost:7000/payments/getPayments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODc5OTNhNjE2OGY1MTIwNDRlOTQxMCIsImVtYWlsIjoic3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9VU0VSIiwiaWF0IjoxNjE5NTA4NDYxfQ.W7DbtVHlYTO95wnEvsEOnHtol4Gg6SmWDQ0UeDtWaew

{
    "userId":"608e589d1c164145787854ae"
}

###
POST http://localhost:7000/payments/getSinglePaymentRecord
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODc5OTNhNjE2OGY1MTIwNDRlOTQxMCIsImVtYWlsIjoic3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9VU0VSIiwiaWF0IjoxNjE5NTAxNTg5fQ.xwJSxamocUUc_g-bQ-a2Tv9MYvkCiIaq_Kwp4j8UR-E

{
    "paymentId":"608f5d2ccc075b35e428cef7"
}

###
PATCH http://localhost:7000/payments/updatePaymentRecord
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODc5OTNhNjE2OGY1MTIwNDRlOTQxMCIsImVtYWlsIjoic3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9VU0VSIiwiaWF0IjoxNjE5NTA4NDYxfQ.W7DbtVHlYTO95wnEvsEOnHtol4Gg6SmWDQ0UeDtWaew

{
        "paymentId":"608f5d2ccc075b35e428cef7",
        "paid" : 1500,
        "dueAmount" : 0
}

###
GET http://localhost:7000/payments/calculateTotalPayment/608e589d1c164145787854ae
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODc5OTNhNjE2OGY1MTIwNDRlOTQxMCIsImVtYWlsIjoic3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9VU0VSIiwiaWF0IjoxNjE5NTA4NDYxfQ.W7DbtVHlYTO95wnEvsEOnHtol4Gg6SmWDQ0UeDtWaew



#   ---------------------------Delivery---------------------------------
###
POST http://localhost:7000/deliveries/createDelivery
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODc5OTNhNjE2OGY1MTIwNDRlOTQxMCIsImVtYWlsIjoic3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9VU0VSIiwiaWF0IjoxNjE5NTAxNTg5fQ.xwJSxamocUUc_g-bQ-a2Tv9MYvkCiIaq_Kwp4j8UR-E

{
    "userId":"608e589d1c164145787854ae",
    "bottleSize" : "1500ml"
}

###
PATCH  http://localhost:7000/deliveries/updateDeliveryRecord
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODc5OTNhNjE2OGY1MTIwNDRlOTQxMCIsImVtYWlsIjoic3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9VU0VSIiwiaWF0IjoxNjE5NTAxNTg5fQ.xwJSxamocUUc_g-bQ-a2Tv9MYvkCiIaq_Kwp4j8UR-E

{
    "deliveryId":"608f5ea4cc075b35e428cefa",
    "bottleSize" : "1500ml"
}

###
POST  http://localhost:7000/deliveries/getDeliveries
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODc5OTNhNjE2OGY1MTIwNDRlOTQxMCIsImVtYWlsIjoic3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9VU0VSIiwiaWF0IjoxNjE5NTAxNTg5fQ.xwJSxamocUUc_g-bQ-a2Tv9MYvkCiIaq_Kwp4j8UR-E

{
    "userId":"608e589d1c164145787854ae"
}


###
GET  http://localhost:7000/deliveries/getDeliveryRecordById/6087a99e9a3f0426b0981191
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODc5OTNhNjE2OGY1MTIwNDRlOTQxMCIsImVtYWlsIjoic3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9VU0VSIiwiaWF0IjoxNjE5NTAxNTg5fQ.xwJSxamocUUc_g-bQ-a2Tv9MYvkCiIaq_Kwp4j8UR-E


###
GET  http://localhost:7000/deliveries/calculateDeliveryCost/608e589d1c164145787854ae
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODc5OTNhNjE2OGY1MTIwNDRlOTQxMCIsImVtYWlsIjoic3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9VU0VSIiwiaWF0IjoxNjE5NTAxNTg5fQ.xwJSxamocUUc_g-bQ-a2Tv9MYvkCiIaq_Kwp4j8UR-E


#----------------REgular Sales -----------------
###
POST http://localhost:7000/sales/createSale
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODc5OTNhNjE2OGY1MTIwNDRlOTQxMCIsImVtYWlsIjoic3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9VU0VSIiwiaWF0IjoxNjE5NTAxNTg5fQ.xwJSxamocUUc_g-bQ-a2Tv9MYvkCiIaq_Kwp4j8UR-E

{
    "paid":1000
}

###
PATCH  http://localhost:7000/sales/updateSaleRecord
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODc5OTNhNjE2OGY1MTIwNDRlOTQxMCIsImVtYWlsIjoic3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9VU0VSIiwiaWF0IjoxNjE5NTAxNTg5fQ.xwJSxamocUUc_g-bQ-a2Tv9MYvkCiIaq_Kwp4j8UR-E

{
    "saleId":"608f5ffd0f87753b84959995",
    "paid":1100
}

###
POST  http://localhost:7000/sales/getSales
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODc5OTNhNjE2OGY1MTIwNDRlOTQxMCIsImVtYWlsIjoic3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9VU0VSIiwiaWF0IjoxNjE5NTAxNTg5fQ.xwJSxamocUUc_g-bQ-a2Tv9MYvkCiIaq_Kwp4j8UR-E



###
GET  http://localhost:7000/sales/totalSales
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODc5OTNhNjE2OGY1MTIwNDRlOTQxMCIsImVtYWlsIjoic3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9VU0VSIiwiaWF0IjoxNjE5NTAxNTg5fQ.xwJSxamocUUc_g-bQ-a2Tv9MYvkCiIaq_Kwp4j8UR-E


###
GET  http://localhost:7000/sales/getSingleSaleRecord/6087ab932dd0833e0ca8bcdd
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODc5OTNhNjE2OGY1MTIwNDRlOTQxMCIsImVtYWlsIjoic3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9VU0VSIiwiaWF0IjoxNjE5NTAxNTg5fQ.xwJSxamocUUc_g-bQ-a2Tv9MYvkCiIaq_Kwp4j8UR-E



# --------------SUPERUSER------------------
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODc4YzBlMzEwZTU5MzA5ODU1NDMwMSIsImVtYWlsIjoidGVzdGVyMDJAZ21haWwuY29tIiwicm9sZSI6IlNVUEVSX1VTRVIiLCJpYXQiOjE2MTk0OTU5NTB9.6TaobT1JQR3aWziyP9DQvjDLFLqAc5iY4hegoRK7aJo
# {
#     "email":"tester02@gmail.com",
#     "name": "Tester02",
#     "age": 22,
#     "password" : "tester1234",
#     "role" : "SUPER_USER"
# }